# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' @title Learn
#' @description An internal function that simulates learning using C++.
#' 
#' @param rep_size Learner repertoire size.
#' @param reps Demonstrator repertoires.
#' @param locs Demonstrator locations.
#' @param loc Learner location.
#' @param t_x Demonstrator attractiveness.
#' @param syl_counter Syllable counter.
#' @param num_dems Number of demonstrators.
#' @param a Level of conformity bias.
#' @param innov Innovation rate.
#' @param p_att Proportion of attractive syllables.
#'
#' @return Returns a one matrix: the Simpson's diversity from each burn-in year (column) and iteration (row).
#'
#' @export
learn <- function(rep_size, reps, locs, loc, t_x, syl_counter, num_dems, a, innov, p_att) {
    .Call('_TransmissionBias_learn', PACKAGE = 'TransmissionBias', rep_size, reps, locs, loc, t_x, syl_counter, num_dems, a, innov, p_att)
}

